kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      custom: gpu
  template:
    metadata:
      labels:
        custom: gpu
    spec:
      containers:
      - name: gpu-container
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1